# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cf19e41c1e6d61cfde125029e6b4e911044c51529079b2942635bde739255e4e15b56116a5f161cf7fe40c375f7739136763900f70a0e27673798df50d0f386

test:
  secret_key_base: 3b7641ce322df47e5072c18bfc384cdcd6adf0645f63611fdf2d48d03ae202906c3898743294731cad54b1fed4285c13172ec5bd3117fb7f1243cff324a89f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
